Round results
wsz82/calibration_management_software pull request #6
Opened 2023-03-05 12:46 UTC by tyn2ka

Round results

2023-03-05 13:24 UTC, wsz82 commented on model/src/main/java/procedure/results/DefaultUncertaintyCalculator.java
> +
Niepotrzebna linijka

2023-03-05 13:24 UTC, wsz82 commented on model/src/main/java/procedure/results/DefaultUncertaintyCalculator.java
> +
Też niepotrzebna pusta linijka

2023-03-05 13:24 UTC, wsz82 commented on model/src/main/java/procedure/results/DefaultUncertaintyCalculator.java
> +
tu też

2023-03-05 13:24 UTC, wsz82 commented on model/src/main/java/procedure/results/DefaultUncertaintyCalculator.java
> +
te też są niepotrzbne

2023-03-05 13:26 UTC, wsz82 requested changes
Proszę usuń niepotrzebne puste linie

2023-03-09 19:48 UTC, tyn2ka commented
Spacje usunięte zrobiłam amen commit i git push -f . Zmiany powinny być już widoczne .

2023-06-03 09:28 UTC, wsz82 approved these changes

2023-06-03 09:29 UTC, merged